name: Docker Build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set date and git sha
        id: vars
        run: |
          echo "GIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV


      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          BRANCH_OR_TAG: ${{ github.base_ref || github.ref_name }}
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.ECR_REGISTRY }}/go-voice-bot:${{ env.DATE }}-${{ env.GIT_SHA }}
            ${{ env.ECR_REGISTRY }}/go-voice-bot:${{ env.BRANCH_OR_TAG }}
          network: host
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: false
          pull: true